### ISSUE TITLE
Display week number in top panel?

### ISSUE THREAD

**Issue by orschiro** [KEIII/gnome-shell-panel-date-format#1]
Dear KEIII,

Can your extension support the displaying of the week number in the top panel?

Thank you very much!

**Comment by KEIII** [comment]
You can use any syntax from here https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format

It looks what you are looking for is

>  %V: the ISO 8601 standard week number of the current year as a decimal number, range 01 to 53, where week 1 is the first week that has at least 4 days in the new year. See g_date_time_get_week_of_year(). This works well with %G and %u.

**Comment by orschiro** [comment]
Thank you very much!

`dconf write /org/gnome/shell/extensions/panel-date-format/format "'%d.%m.%y (%V) %H:%M'"` has translated well. 

I appreciate your help!

![image](https://user-images.githubusercontent.com/170947/43830438-8493c0fa-9b01-11e8-89bd-041bdf1bb48e.png)
