### ISSUE TITLE
Print simple date calculation on the panel

### ISSUE THREAD

**Issue by lamyergeier** [KEIII/gnome-shell-panel-date-format#10]
For example, I would like to calculate the percentage of days left in a year, and show up in the panel, next to the date. 

It will be useful as sometimes it is hard to visualize how much of the time has passed away. With a percentage it will be easy to know, how much we have spent till this year end.

Is it possible?

**Comment by KEIII** [comment]
I believe it's not possible cuz no calculations allowed by `strftime()` https://docs.gtk.org/glib/method.DateTime.format.html
