### ISSUE TITLE
The date format is being cloned, and the original one will be restored after restarting the OS.

### ISSUE THREAD

**Issue by kanansnote** [KEIII/gnome-shell-panel-date-format#11]
I'm having problems using the extension since it causes odd bugs like [this](https://drive.google.com/file/d/1QzcgXAA44CNWidahQJtK_mJlE13EJ1lg/view?usp=share_link). Restarting the extension is unlikely to solve the issue, so hopefully you'll fix this as soon as possible. Thanks.

**Comment by KEIII** [comment]
Could you please provide gnome shell and extension version?
Just suppose it might be a conflict with another extension.
Could you try to disable it and give me feedback?

**Comment by kanansnote** [comment]
[Here it is.](https://drive.google.com/file/d/1xsZpFYn4Yolu14qcP0jEh7Qs_04slGCS/view?usp=share_link)

So, I deactivated it yesterday and reactivated it today. It appears to be working now, but I suspect it is only temporary, as it can break the extension again.

Update: As an experiment, I locked and restarted the OS, and [the problem](https://drive.google.com/file/d/1EWANHnlxcM0qcrmtXcFM9hlEskhKO0TD/view?usp=share_link) reappeared.

**Comment by KEIII** [comment]
For now it's pretty hard to say why it may happens. I can't reproduce it on Ubuntu 22.04

![Screenshot from 2023-03-15 14-04-24](https://user-images.githubusercontent.com/1167833/225292339-dc838193-d5a9-4850-87bb-92cce6eb64e6.png)

**Comment by kanansnote** [comment]
Alright. So, then I think there could be the reason of having a lot of extensions, which one of them are conflicting with this one. And I don't really know what it is :(.
