### ISSUE TITLE
Problem in Ubuntu 22.04.2

### ISSUE THREAD

**Issue by Banellica** [KEIII/gnome-shell-panel-date-format#12]
I have installed this gnome extension.
Then:
`~$ gnome-extensions enable panel-date-format@keiii.github.com`

returned with no error message. 
Then:

`dconf write /org/gnome/shell/extensions/panel-date-format/format "'%A %-d %B %Y %k:%M (%:z)'"`

returned with no error; **but there is no change at the top bar title**.

```
~$ gnome-shell --version
GNOME Shell 42.5
```

System: Ubuntu 22.04.2; 
Kernel: Linux 5.19.0-41-generic #42~22.04.1-Ubuntu

**Comment by KEIII** [comment]
Do you have any other enabled extensions?
Causes it looks like conflict with another one.
For me '%A %-d %B %Y %k:%M (%:z)' works well on clean Ubuntu 22.04 installation.
