### ISSUE TITLE
Possible to Adjust Size of Date Panel Text?

### ISSUE THREAD

**Issue by AlexLandherr** [KEIII/gnome-shell-panel-date-format#14]
Hi,

I'm running this Debian setup:
```
alexl@PD70PNP:~$ neofetch
       _,met$$$$$gg.          alexl@PD70PNP 
    ,g$$$$$$$$$$$$$$$P.       ------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: PD5x_7xPNP_PNR_PNN_PNT 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-13-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 3 hours, 26 mins 
 $$P      d$'     ,    $$P    Packages: 1887 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: GNOME 43.6 
 `$$b      "-.__              WM: Mutter 
  `Y$$                        WM Theme: Adwaita 
   `Y$$.                      Theme: Adwaita [GTK2/3] 
     `$$b.                    Icons: Adwaita [GTK2/3] 
       `Y$$b.                 Terminal: gnome-terminal 
          `"Y$b._             CPU: 12th Gen Intel i7-12700H (20) @ 4.600GHz 
              `"""            GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
                              GPU: Intel Alder Lake-P 
                              Memory: 2450MiB / 15693MiB
```

and am wondering whether there's a way to change size of the date panel text to be smaller or larger than the default?

**Comment by KEIII** [comment]
Hi. There is no built-in option to change the font size. The extension does not modify the original styles, only the format.

However, you can change the font size of the panel, by adjusting the font size option in the [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/) (Fine-Tune > Tray Font Size).

If you want to change the size of the date panel text without using the extension, you would need to create or modify a custom theme and use CSS styles. You can find instructions on GNOME forums [like this](https://superuser.com/questions/107408/how-to-change-font-size-in-gnome-shell-panel).

**Comment by AlexLandherr** [comment]
Thanks for the info! I think I'll stick with the default from this extension.
