### ISSUE TITLE
No way to customise format on Fedora 39, Gnome 45

### ISSUE THREAD

**Issue by Kokkolis** [KEIII/gnome-shell-panel-date-format#15]
I have installed and unistalled it, it appears installed, but there are no settings menu anywhere. Changes format to "2024.month.date.time" but there isn't a settings menu anywhere to change the format to whatever I want it to be. Thank you.
![Panel date format 1](https://github.com/KEIII/gnome-shell-panel-date-format/assets/45275198/d35e556e-966f-4593-97cb-14d59cf83c4b)
![Panel date format 2](https://github.com/KEIII/gnome-shell-panel-date-format/assets/45275198/54a4e032-6b9b-4f1c-aee4-ee5a685dcbef)

**Comment by KEIII** [comment]
There is no GUI settings by design.

You have to use dconf editor to change a format:
/org/gnome/shell/extensions/panel-date-format/
![image](https://github.com/KEIII/gnome-shell-panel-date-format/assets/1167833/ce36e488-7f07-4763-8254-e0748d452b83)

or simply from the terminal:
https://github.com/KEIII/gnome-shell-panel-date-format?tab=readme-ov-file#changing-format

**Comment by Kokkolis** [comment]
Hello, thank you for the clarification, I have now managed to make a change. Two questions please:
1. How is it possible to have the single date displayed as ONE digit and not two (i.e. today -using UK date format) it's the 8th of February, how do you make it show as "8" and not "08"?, and 
2. The change I have made using the panel-date-format- now shows the correct format on the top of the taskbar (apart of the "08" -instead of just "8"), but the date format inside the Calendar is still wrong (should display "Thu 8 Feb 2024", but it displays "Thu Feb 8 2024" (US format, not UK or Greek). How could this change?
have tried to illustrate with an attached pic. Thank you for your great work and contribution (from a complete novice..).
Very grateful.
Kind regards,Christos


    Στις Τετάρτη 7 Φεβρουαρίου 2024 στις 05:42:47 μ.μ. GMT, ο χρήστης Ivan Kasenkov ***@***.***> έγραψε:  
 
 


There is no GUI settings by design.

You have to use dconf editor to change a format:
/org/gnome/shell/extensions/panel-date-format/
image.png (view on web)

or simply from the terminal:
https://github.com/KEIII/gnome-shell-panel-date-format?tab=readme-ov-file#changing-format

**Comment by KEIII** [comment]
I guess 

> %e: the day of the month as a decimal number (range 1 to 31); single digits are preceded by a figure space (U+2007)

You can see all posible formats on GLib.DateTime page here https://docs.gtk.org/glib/method.DateTime.format.html

**Comment by KEIII** [comment]
Unfortunately there is no way to change format inside the Calendar, at least this extension can't do that.
