### ISSUE TITLE
Some locale such as fr_FR define the first letter of any word in lower case, which is not aesthetically nice.

### ISSUE THREAD

**Issue by deragon** [KEIII/gnome-shell-panel-date-format#19]
Some locale such as `/usr/share/i18n/locales/fr_FR`, have, for reasons I do not know, all the word starting in lower case, instead of upper case like `/usr/share/i18n/locales/en_US` for instance.

Thus, the date, as I configured, shows up like '_dimanche, 2024-09-01 15:27:32_'.  Not nice.  I want **Dimanche**, with a capital letter (BTW, Dimanche == Sunday).

I suggest that the code puts automatically an upper case for any of the Words generated by the formatting options like %A for example.

**Comment by KEIII** [comment]
The extension implementation is straightforward
Its utilize buildin GLib.DateTime format() function
https://github.com/KEIII/gnome-shell-panel-date-format/blob/master/extension.js#L55
There is no plan to add extra feature, but anyone feel free to fork the extension.
