### ISSUE TITLE
ISO 8601 allows +hh and -hh

### ISSUE THREAD

**Issue by MarkSenn** [KEIII/gnome-shell-panel-date-format#2]
Thanks for the handy software!  ISO 8601 allows +hh and -hh for time offsets.  Right now the time in New York city is approximately 20:52 -05.  If +hh and -hh could be added I'd appreciate it.  Thanks for reading.

**Comment by KEIII** [comment]
The extension itself does't do date format, but uses `strftime()` under the hood. So you can use any supported format https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format
It's may be helpful:
```
%z: the time zone as an offset from UTC (+hhmm)
%:z: the time zone as an offset from UTC (+hh:mm). This is a gnulib strftime() extension. Since: 2.38
%::z: the time zone as an offset from UTC (+hh:mm:ss). This is a gnulib strftime() extension. Since: 2.38
%:::z: the time zone as an offset from UTC, with : to necessary precision (e.g., -04, +05:30). This is a gnulib strftime() extension. Since: 2.38
```

**Comment by KEIII** [comment]
It seem nothing to do here.
