### ISSUE TITLE
Update for Gnome 47

### ISSUE THREAD

**Issue by Pseudavid** [KEIII/gnome-shell-panel-date-format#20]
Please update the extension for Gnome 47.
I just tested changing the version in metadata.json to 47, and the extension seems to work.
Thank you very much for this extension. It's one of my essentials. For me, having the time on a prominent location on screen is quite intrusive, I don't want to know the exact time at all times (lol). This extension is the only way to change that.

**Comment by KEIII** [comment]
Updated
