### ISSUE TITLE
Easier configuration, please

### ISSUE THREAD

**Issue by hackerb9** [KEIII/gnome-shell-panel-date-format#4]
I am very thankful for this extension as the inability to change the formatting was extremely frustrating for an elderly gentleman I just helped over the phone. We did manage, using this extension, to configure his date and clock to work the way he prefers, but it was _way_ too hard for him. I think the hardest two problems were:

1. The [documentation](https://docs.gtk.org/glib/method.DateTime.format.html) is terrible as it formats the escape characters haphazardly. Some of them are missing the leading percent and are instead surrounded by backticks. 
2. Using the command line is not natural for many people. In particular, editing a previous line when it wasn't quite right caused the gentleman I was helping to keep trying to use his mouse even if I was saying, "tap the up arrow key". 

Suggestions:

* Let users type the formatting string in a text entry field that updates the clock immediately so they can easily notice and fix typos before closing it.
* Maybe add a Settings icon in the panel that pops open when a user click on the clock that will bring up the gnome-shell-panel-date-format configuration panel.
* Underneath the panel it would be good to have a list of all possible percent escape with not only a short summary of what each does, but a live example of what it currently evaluates to. (E.g., `%B  |  Long month name  |  November`).
* Underneath that list of options, but before the [CANCEL] and [APPLY] buttons, it would be great to have buttons for various commonly used settings. The button text could actually be a live example so a person can just recognize what they want and click on it. 

Thank you for the handy extension!

**Comment by KEIII** [comment]
Thanks for feedback. 

Sad but true I'm too lazy support graphical user interface for this extension. I'm personally never ever change date format since reinstall os. Hopefully one day we got this feature in Gnome out the box ;-)

For now you can try another extension with UI https://github.com/atareao/panel-date-format

**Comment by hackerb9** [comment]
Atareao's fork of your code looks like what I was asking for. Thanks!

(And, yes, this is the sort of thing that should be included in Gnome).
