### ISSUE TITLE
add gnome 42 support

### ISSUE THREAD

**Issue by mhkarimi1383** [KEIII/gnome-shell-panel-date-format#5]
I want to know if we are able to do it by just a simple change in metadata?

**Comment by KEIII** [comment]
I have no tested yet. Could you please update  `$HOME/.local/share/gnome-shell/extensions/panel-date-format@keiii.github.com/metadata.json` on your local machine with Gnome 42? Restart gnome-shell after that needed I guess. If it still works nothing more changes required.

**Comment by mhkarimi1383** [comment]
Worked,
clone from github using 
```bash
git clone https://github.com/KEIII/gnome-shell-panel-date-format $HOME/.local/share/gnome-shell/extensions/panel-date-format@keiii.github.com/
```
changed metadata and added new version

**Comment by KEIII** [comment]
Good to know. Thank you. I've been uploaded new version to extensions.gnome.org
