### ISSUE TITLE
Increased side margin after update

### ISSUE THREAD

**Issue by siddhpant** [KEIII/gnome-shell-panel-date-format#8]
The side margins have increased after updating to new version.

---

Old (from a screenshot):

![image](https://user-images.githubusercontent.com/25429745/182587546-90141d2a-6050-41aa-9ac4-8fcd6e47580d.png)

---

New:

![image](https://user-images.githubusercontent.com/25429745/182587616-c854d273-897e-4565-802e-a5717c4e3f32.png)

Hovering over it looks like this:

![image](https://user-images.githubusercontent.com/25429745/182587849-b61dd07e-ecd4-4091-9542-6fc07e671d60.png)

**Comment by siddhpant** [comment]
Theme: https://www.gnome-look.org/p/1012901

**Comment by KEIII** [comment]
Since last commit original styles are used. So I would say it's looks native now.
Does this theme have same issue with disabled extension?

**Comment by siddhpant** [comment]
> Since last commit original styles are used. So I would say it's looks native now.

Oh, that makes sense.

> Does this theme have same issue with disabled extension?

Yes, indeed it has. Sorry for the noise!

I just add this extension everytime since it provides essential functionality, so I hadn't even bothered to look at (or forgot) the default style.
